# Opt-in (enable_workbook): the Azure Workbook from workbooks/, generated by scripts/build_workbook.py from the same
# KQL files the CLI runs (Resource Graph data source). Workbooks are free; it shows whatever the viewer can read.
resource "azurerm_application_insights_workbook" "waste_finder" {
  count = var.enable_workbook ? 1 : 0

  # The name must be a GUID; uuidv5 keeps it stable per prefix, so a re-apply updates the same workbook.
  name                = uuidv5("url", "https://github.com/viache25/azure-waste-finder/workbook/${var.prefix}")
  resource_group_name = local.resource_group_name
  location            = local.location
  display_name        = "Azure Waste Finder (${var.prefix})"
  description         = "Resources that cost money but do nothing: the Resource Graph queries of azure-waste-finder."
  category            = "workbook"
  source_id           = "azure monitor" # shared workbook in Azure Monitor > Workbooks, not tied to one resource
  data_json           = file("${path.module}/../workbooks/waste-finder.workbook.json")
  tags                = local.tags
}
